### ISSUE TITLE
fix is always false

### ISSUE THREAD

**Issue by kimalser** [esdalmaijer/PyTribe#2]
Please, remove =='true' from the line 850.
I guess string comparison fails there so the program logs 'false' for all entries.

**Comment by esdalmaijer** [comment]
Good point, I've been meaning to get to this. I was under the assumption that the EyeTribe Server would provide string-based Booleans, but it seems these were properly recognised as actual (True/False) Booleans.

**Comment by esdalmaijer** [comment]
Solved with the [latest commit](https://github.com/esdalmaijer/PyTribe/commit/e3e773652e068ee545f98fb18fccaf25b2240117).
